import css from "css"
import fs from "fs"

/**
 * Utility function, parse a given filename
 *
 * @param {String} filename
 * @returns {AST}
 */
export const parseFile = filename =>
  parse(fs.readFileSync(filename, "utf8"))

/**
 * Parse raw CSS sources
 *
 * @param {String} data
 * @returns {AST} generated by package css
 */
export const parse = data => css.parse(data)

/**
 * Get CSS rule nodes from AST
 *
 * @param {AST} ast
 * @returns {Array}
 */
export const getRules = ast => ast.stylesheet.rules

